# Generated by Django 4.2.14 on 2024-07-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Product"},
        ),
    ]
