# Generated by Django 4.2.14 on 2024-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="chihama.jpg", upload_to="Profile_images"),
        ),
    ]
